#!/bin/bash



 ./ps.pl > /dev/null

 grep @@ output.csv |sort -t, -k3 -k1n |awk -F, '{if ($6 > .19) \
	 print $1","$2,","$3","$6}' |column -s, -t
echo ----

 ntpq -pn |egrep -i 'init|local|^x|[0-9]h|[0-9]m'
 ntpq -pn burgess |egrep -i 'init|local|^x|[0-9]h|[0-9]m' 
