#!/bin/bash

PFX='/var/log/ntpstats/remote/burgess'

for f in  $PFX/peerstats.2021w{25..52}; do
	echo $f;
	for x in `cat $f |grep 127.127.28.1 |awk -v T="$1" '{if ($8 > T) print $2}'`; 
		do echo $x;sed -i /$x/d $f ;done
	done;


